import type { Spot, CreateSpotInput, UpdateSpotInput, SearchFilters } from '@/types';
import { getDB, type QueuedMutation } from './idb-schema';
import { DataStore } from './datastore';

// ---------------------------------------------------------------------------
// Sync: download all spots from Supabase into IndexedDB
// ---------------------------------------------------------------------------

/**
 * Download the full spot list from Supabase and replace all cached spots
 * in IndexedDB. This is the primary "pull" sync operation.
 *
 * Returns the number of spots synced.
 */
export async function syncSpots(): Promise<number> {
  const spots = await DataStore.listSpots();
  const db = await getDB();

  const tx = db.transaction('spots', 'readwrite');
  // Clear stale data
  await tx.store.clear();
  // Write all fresh spots
  for (const spot of spots) {
    await tx.store.put(spot);
  }
  await tx.done;

  // Persist the last-sync timestamp
  const metaTx = db.transaction('meta', 'readwrite');
  await metaTx.store.put({ key: 'lastSync', value: Date.now() });
  await metaTx.done;

  return spots.length;
}

/**
 * Get the timestamp (ms since epoch) of the last successful sync,
 * or null if the cache has never been populated.
 */
export async function getLastSyncTime(): Promise<number | null> {
  const db = await getDB();
  const meta = await db.get('meta', 'lastSync');
  return meta ? (meta.value as number) : null;
}

// ---------------------------------------------------------------------------
// Offline reads
// ---------------------------------------------------------------------------

/**
 * Read all cached spots from IndexedDB.
 */
export async function getCachedSpots(): Promise<Spot[]> {
  const db = await getDB();
  return db.getAll('spots');
}

/**
 * Read a single cached spot by ID.
 */
export async function getCachedSpot(id: string): Promise<Spot | undefined> {
  const db = await getDB();
  return db.get('spots', id);
}

/**
 * Filter cached spots using the same SearchFilters interface
 * that the online SearchEngine uses.
 *
 * This mirrors the client-side filtering logic from search-engine.ts
 * so that offline search behaves identically to the online proximity path.
 */
export async function searchCachedSpots(filters: SearchFilters): Promise<Spot[]> {
  let spots = await getCachedSpots();

  if (filters.district) {
    spots = spots.filter(
      (s) => s.district.toLowerCase() === filters.district!.toLowerCase(),
    );
  }

  if (filters.categories && filters.categories.length > 0) {
    const catSet = new Set(filters.categories);
    spots = spots.filter((s) => catSet.has(s.category));
  }

  if (filters.minRating) {
    spots = spots.filter(
      (s) => s.rating !== undefined && s.rating >= filters.minRating!,
    );
  }

  if (filters.query) {
    const q = filters.query.toLowerCase();
    spots = spots.filter(
      (s) =>
        s.name.toLowerCase().includes(q) ||
        (s.notes && s.notes.toLowerCase().includes(q)),
    );
  }

  return spots;
}

// ---------------------------------------------------------------------------
// Mutation queue (offline writes)
// ---------------------------------------------------------------------------

/**
 * Enqueue a mutation to be replayed when the app is back online.
 * The queueId is auto-generated by IndexedDB.
 */
async function enqueueMutation(
  mutation: Omit<QueuedMutation, 'queueId'>,
): Promise<void> {
  const db = await getDB();
  await db.add('mutations', mutation as QueuedMutation);
}

/**
 * Get the number of pending mutations in the queue.
 */
export async function getPendingMutationCount(): Promise<number> {
  const db = await getDB();
  return db.count('mutations');
}

/**
 * Get all pending mutations, ordered by timestamp (ascending).
 */
export async function getPendingMutations(): Promise<QueuedMutation[]> {
  const db = await getDB();
  return db.getAllFromIndex('mutations', 'by-timestamp');
}

/**
 * Create a spot while offline.
 * Generates a temporary UUID, applies the change to the local cache,
 * and enqueues the mutation for later sync.
 */
export async function offlineCreateSpot(input: CreateSpotInput): Promise<Spot> {
  const now = new Date().toISOString();
  const tempId = `offline-${crypto.randomUUID()}`;

  const spot: Spot = {
    id: tempId,
    name: input.name,
    location: input.location,
    district: '', // will be resolved on server sync
    category: input.category,
    customCategory: input.customCategory,
    rating: input.rating,
    notes: input.notes,
    visitDate: input.visitDate ?? now.slice(0, 10),
    photoUrls: input.photoUrls ?? [],
    createdAt: now,
    updatedAt: now,
  };

  // Write to local cache
  const db = await getDB();
  await db.put('spots', spot);

  // Queue mutation
  await enqueueMutation({
    id: tempId,
    type: 'create',
    data: input,
    timestamp: Date.now(),
  });

  return spot;
}

/**
 * Update a spot while offline.
 * Applies the partial update to the local cache and enqueues the mutation.
 */
export async function offlineUpdateSpot(
  id: string,
  input: UpdateSpotInput,
): Promise<Spot> {
  const db = await getDB();
  const existing = await db.get('spots', id);

  if (!existing) {
    throw new Error(`Spot ${id} not found in offline cache`);
  }

  const updated: Spot = {
    ...existing,
    name: input.name ?? existing.name,
    category: input.category ?? existing.category,
    customCategory: input.customCategory ?? existing.customCategory,
    rating: input.rating ?? existing.rating,
    notes: input.notes ?? existing.notes,
    visitDate: input.visitDate ?? existing.visitDate,
    photoUrls: input.photoUrls ?? existing.photoUrls,
    updatedAt: new Date().toISOString(),
  };

  await db.put('spots', updated);

  await enqueueMutation({
    id,
    type: 'update',
    data: input,
    timestamp: Date.now(),
  });

  return updated;
}

/**
 * Delete a spot while offline.
 * Removes from the local cache and enqueues the mutation.
 */
export async function offlineDeleteSpot(id: string): Promise<void> {
  const db = await getDB();
  await db.delete('spots', id);

  await enqueueMutation({
    id,
    type: 'delete',
    timestamp: Date.now(),
  });
}

// ---------------------------------------------------------------------------
// Flush mutation queue (replay offline changes)
// ---------------------------------------------------------------------------

/**
 * Replay all queued mutations against the Supabase backend.
 *
 * Mutations are applied in timestamp order. Each successful mutation
 * is removed from the queue. If a mutation fails, we stop and throw
 * so the caller can retry later.
 *
 * Returns the number of mutations successfully applied.
 */
export async function flushMutationQueue(): Promise<number> {
  const mutations = await getPendingMutations();
  if (mutations.length === 0) return 0;

  const db = await getDB();
  let applied = 0;

  for (const mutation of mutations) {
    switch (mutation.type) {
      case 'create': {
        const input = mutation.data as CreateSpotInput;
        const created = await DataStore.createSpotWithDistrict(input, '');
        // Replace the temporary offline spot with the real server-assigned one
        await db.delete('spots', mutation.id);
        await db.put('spots', created);
        break;
      }

      case 'update': {
        // Skip updates for offline-created spots (they have a temp ID
        // and would have been replaced during the create flush above).
        if (!mutation.id.startsWith('offline-')) {
          const updateInput = mutation.data as UpdateSpotInput;
          const updated = await DataStore.updateSpot(mutation.id, updateInput);
          await db.put('spots', updated);
        }
        break;
      }

      case 'delete': {
        // Skip deletes for offline-created spots that never reached the server
        if (!mutation.id.startsWith('offline-')) {
          await DataStore.deleteSpot(mutation.id);
        }
        break;
      }
    }

    // Remove this mutation from the queue
    if (mutation.queueId !== undefined) {
      await db.delete('mutations', mutation.queueId);
    }

    applied++;
  }

  return applied;
}
